# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edf43059aba923136296c1dfc72ff4efaae7b337a2cfbb50325cac54ace99f4d45f68d3cba10605fe4370b061da162170e3f3ad8cc1f15399c0eff1bed5f839f

test:
  secret_key_base: d1b5ec412a47a348d6d4834a32f731517ac3270685b1ad3e3ba910a37368e5b67e0822663860daf2c630f3f6488be3e6518a8e85e43036333d55c4a69f438859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
